version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: monthly
      time: '11:07'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: '11:07'