name: Deploy Hacker Laws Website
on:
  push:
    paths:
      - hacker-laws
      - .github/workflows/deploy.yaml
    branches-ignore:
      - dependabot/**
  pull_request:
    paths:
      - hacker-laws
      - .github/workflows/deploy.yaml
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          persist-credentials: false
          
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hacker-laws
          enable_jekyll: true
          cname: hacker-laws.44444444.xyz