name: Website Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Website
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hacker-laws
          enable_jekyll: true
          cname: hacker-laws.114913.xyz